### PR TITLE
use python native Gzip

### PR DESCRIPTION
**Pull request by justinturpin**
Uses Python Native GZIP functionality, which will aid in this randomizer being cross-platform and eliminate the need to bundle a binary executable with the repo.

### CODE REVIEW

**Comment by CyrusKashef** [comment]
I ran the rando with the current code and with the code you're attempting to push in, everything else as the same setting, and when I compared the ROM files, they were different. Btw, I appreciate you trying to help out with the randomizer ^_^ Feel free to contact me on Discord if you'd like to talk.

**Comment by justinturpin** [comment]
Okay I'll hit you up there from the username ionstream! I did run the ROM's outputted from this branch, and they worked, but I'll check and see what the differences are to make sure its all deterministic.

**Comment by CyrusKashef** [comment]
I might try it this weekend and see if I notice any major changes 🤔

**Comment by justinturpin** [comment]
So I took a look at the output of pythons gzip.GzipFile vs the Gnu Gzip.exe and, when Python's compresslevel is set to 6 (the default is 9), the data payload is the same, with only the headers metadata being different. I can set the compresslevel to 6 if you want to maintain equivalence there but I'm not sure it matters to the game.

**Comment by justinturpin** [comment]
After a lot of research it seems that the zlib-based implementation of Gzip that Python uses produces files that are just ever so slightly too large to fit into the randomizer. There are ways to make it work, such as compressing the files multiple times but with different settings and picking the smallest output, but we're getting into hack territory there. I will keep the fork alive if anyone finds it useful and wants to run it on Linux/MacOS.

**Pull request closed without merging**
